# Generated by the Live Palette addon from res://live_palette/*.tres.
# Do not edit — it is rewritten whenever a palette changes.
class_name LivePalette

## The constants are the "Default" variant; switching variants at runtime goes
## through the LivePaletteRuntime autoload, which re-applies bound properties.
const COLLISIONS := Color(0, 0.12156863, 0.77254903, 0.54901963)
const HURTBOXES := Color(0.79607844, 0.49019608, 0.05490196, 0.6)
const HITBOXES := Color(0.91764706, 0, 0, 0.5882353)
const HEALBOXES := Color(0.14117648, 0.8117647, 0, 0.56078434)

## Palette name -> color, for lookups by a name held in a variable.
## Prefer the constants above: they are checked at compile time.
const BY_NAME := {
	"Collisions": COLLISIONS,
	"Hurtboxes": HURTBOXES,
	"Hitboxes": HITBOXES,
	"Healboxes": HEALBOXES,
}

## Variant name -> {name -> color}, for reading a variant you are not on.
const VARIANTS := {
	"Default": {
		"Collisions": Color(0, 0.12156863, 0.77254903, 0.54901963),
		"Hurtboxes": Color(0.79607844, 0.49019608, 0.05490196, 0.6),
		"Hitboxes": Color(0.91764706, 0, 0, 0.5882353),
		"Healboxes": Color(0.14117648, 0.8117647, 0, 0.56078434),
	},
}


static func color(p_name: StringName) -> Color:
	var key := str(p_name)
	if BY_NAME.has(key):
		return BY_NAME[key]
	push_warning("LivePalette: no color named '%s'" % p_name)
	return Color.WHITE


static func has_color(p_name: StringName) -> bool:
	return BY_NAME.has(str(p_name))


## A color from a specific variant, falling back to the base variant.
static func color_in(p_variant: StringName, p_name: StringName) -> Color:
	var table: Dictionary = VARIANTS.get(str(p_variant), {})
	if table.has(str(p_name)):
		return table[str(p_name)]
	return color(p_name)


static func variant_names() -> PackedStringArray:
	return PackedStringArray(VARIANTS.keys())
